import type { Metadata } from "next";
import "./globals.css";
import { recklessNeue } from "../lib/fonts";
import ClientLayout from "../components/client-layout";
import { Caveat } from "next/font/google";

export const metadata: Metadata = {
  title: "Portfolio - R4V3NSH4DOW",
  description: "Generated by create next app",
};

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-caveat",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${recklessNeue.variable} ${caveat.variable} antialiased`}
      >
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
